### ISSUE TITLE
Smaller spacing units

### ISSUE THREAD

**Issue by gilesbutler** [truefrontier/tailwindcss-golden-ratio#2]
Hi @kevnk,

I stumbled across your plugin via NPM, it looks awesome and I hope this is the right place to ask a question.

I'm no expert on the Golden Ratio so this might be wrong. Someone told me it's very closely linked to the [Fibonacci sequence](https://en.wikipedia.org/wiki/Fibonacci_number) and that I should use the Fibonacci sequence as spacing units in my designs. Since I've been doing that my designs just seem to work and look a lot tighter. 

On previous projects I've just changed tailwind's spacing scale to crudely use the Fibonacci sequence. After stumbling across your plugin though I wondered if there was a better way. Having installed it though and I'm finding the smallest units e.g `py-grp-half-1` or `px-grp-1` are actually coming out pretty big, compared to what I need anyway. Is this correct or am I doing something wrong ha? The screenshot is a button I created using the previous mentioned classes.

![CleanShot 2021-02-23 at 14 34 00@2x](https://user-images.githubusercontent.com/790734/108799463-7a502c80-75e4-11eb-8a6d-e4c27dc8eff3.jpg)

Would love to hear your thoughts and thanks again.

**Comment by kevnk** [comment]
Hey @gilesbutler!

That's right. Awesome to hear someone else get on the Golden Ration kick ;)

I've set this up so you have two options... a `rem` spacing and `percentage` spacing. I see you're using the percentage-based version. If I were you, I'd consider using the `rem` version. 

I might change this in the future, but currently, the default of this plugin is to replace all of tailwind's default spacing with golden ratio. So `px-6` is padding left and right of 1rem, 7 is 1.618rem, 5 is 0.618rem and so on. 

If I were you though, I'd consider using the `prefix` option so `px-6` keeps tailwind's default and `px-gr-6` is the golden ratio version as I just explained above:

```js
module.exports = {
    theme: {
        goldenRatio: {
            prefix: true,
        },
    },
};
```

Does that all make sense?

**Comment by gilesbutler** [comment]
Hey @kevnk,

Thanks for getting back to me and for the detailed response.

Ah I wasn't aware you could pass in options like that to the plugin. It looks like it defaults to percentage spacing then is that correct? 

I've switched to `rem` with the following setup, looks like you have to disable `useCssVars` as well?

```
theme: {
    goldenRatio: {
      prefix: true,
      spacerUnit: "rem",
      useCssVars: false,
    }
}
```

The `prefix` option definitely helps, it's great to know when you're using the golden ration as opposed to Tailwind's built in classes.

Is it possible to apply the spacing to `borderRadius` too?

Thanks

Giles

**Comment by kevnk** [comment]
I hadn't thought of `borderRadius` before... I'll consider that... if you're curious, have a look at [index.js](https://github.com/truefrontier/tailwindcss-golden-ratio/blob/master/index.js) to see the source code I used to create the values. You could employ the same method if you wanted in your tailwind.config.js

**Comment by gilesbutler** [comment]
Awesome thanks @kevnk! I'll take a look.

**Comment by kevnk** [comment]
Happy to help!

All the best!
Kevin Kirchner

Helping business owners forge new revenue streams using web-apps  /// 
TRUE FRONTIER  »  truefrontierapps.com <https://truefrontierapps.com/>




On February 24, 2021, Giles Butler <notifications@github.com> wrote:
> Awesome thanks @kevnk <https://github.com/kevnk>! I'll take a look.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/truefrontier/tailwindcss-golden-
ratio/issues/2#issuecomment-785484500>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAJAN3BETQJRXRCBQA3HIZTTAWKKBANCNFSM4YBW2VLA>.
